# ✪✪✪✪✪

In [9]:
import numpy as np

arr = np.arange(15)
print(type(arr), arr) # 동일한 type 의 데이터만 들어감
print('차원 : ' , np.ndim(arr)) # 차원 출력 , arr.ndim
print('shape : ', np.shape(arr)) # (15, ) arr.shape
print('전체 데이터 갯수 : ', arr.size)
print('데이터 타입 : ', arr.dtype)

# 차원을 변경 -> 15 => (3,5)
arr_ch = arr.reshape(3,5)
print(np.ndim(arr_ch) , arr_ch.shape)
arr_ch

<class 'numpy.ndarray'> [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
차원 :  1
shape :  (15,)
전체 데이터 갯수 :  15
데이터 타입 :  int64
2 (3, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
list_a = list(range(15)) # 여러개의 type의 데이터가 들어감 ['test' , 1 , False ]
print(list_a)
np.shape(np.array(list_a)) # 그냥 np.shape 시 오류 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


(15,)

In [12]:
print(arr.dtype.name , arr.dtype.itemsize)

arr_2 = np.arange(0.0 , 15.0 , 1.0)
print(arr_2.dtype.name , arr_2.dtype.itemsize)

int64 8
float64 8


In [13]:
a1 = np.array([1.0, 2.0, 3.0])
a2 = np.array([[1.0, 2.0],[ 3.0, 4.0]])
print(a1, type(a1))
print(a2, type(a2))
print(a1.ndim, a1.shape, a1.size, a1.dtype)
print(a2.ndim, a2.shape, a2.size, a2.dtype)

[1. 2. 3.] <class 'numpy.ndarray'>
[[1. 2.]
 [3. 4.]] <class 'numpy.ndarray'>
1 (3,) 3 float64
2 (2, 2) 4 float64


In [25]:
# Numpy - Inf 와 NaN, 초기값을 설정한 배열 생성
# 무한대 > np.inf
# Nan -> np.nan

# 초기값을 0으로 부여하면서 배열 생성
print(np.zeros(5))
print(np.zeros((2,3))) # 2 * 3
print(np.zeros((5,2) , dtype = 'i'))
a = np.zeros((5,2) , dtype = 'U4') # U -> object
print(a.dtype , a.dtype.itemsize)

b = np.ones((2,3,4), dtype = 'i8')
print(b)
print()
print(np.ones_like(np.zeros(5), dtype = 'i'))
print()
print(np.empty((2,3)))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
<U4 16
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]

[1 1 1 1 1]

[[0. 0. 0.]
 [0. 0. 0.]]


In [32]:
# array 연산
x1 = np.array([1,2,3])
y1 = np.array([5,10,15])
x2 = np.array([[1,2],[3,4]])
y2 = np.array([[5,10],[15,20]])
z1 = np.array([-1,-2])
z2 = np.array([[5],[10],[15]])

(3, 1)

In [36]:
print(x1 + y1)
print()
print(x2 + y2)
print()
print(x2 + z1) # ndarray broadcast
print()
print(x1 + z2)
print()
print(x1 ** 2) # [1, 4, 9]
print(x1[x1 >= 2]) # [2 , 3] => x1 [[True , False , ...]]

[ 6 12 18]

[[ 6 12]
 [18 24]]

[[0 0]
 [2 2]]

[[ 6  7  8]
 [11 12 13]
 [16 17 18]]

[1 4 9]
[2 3]


In [43]:
# shape 을 변경 -> 1차원으로 변경하는 함수 : x.flatten()
# 모든 차워늘 1차원으로 변경 : 평탄화 한다, flatten()
a1 = x2.reshape(x2.size)
a2 = x2.flatten()
print(a1.shape, a2.shape)

print(a2.reshape((2,2)))

(4,) (4,)
[[1 2]
 [3 4]]


In [45]:
# array 의 일부 데이터 가져오기
a = np.arange(10) ** 2
print(a, 'a[2] -> ', a[2])
print(a[3:5]) # 5는 포함하지 않음 3 과 4의 인덱스의 값만 추출
a[0:6:2] = -a[0:6:2]
print(a)
print(a[: : -1]) # 역순으로 출력

[ 0  1  4  9 16 25 36 49 64 81] a[2] ->  4
[ 9 16]
[  0   1  -4   9 -16  25  36  49  64  81]
[ 81  64  49  36  25 -16   9  -4   1   0]


In [47]:
a = np.arange(1,21).reshape(4,5)
a
# 3행 4열의 값
print(a[3,4]) # 20

# 처음부터 2행, 2열과 3열의 자료 추출
print(a[0:3, 2:4])

# 1행의 모든 자료 추출
print(a[1, :])

# 마지막행의 마지막 열의 값을 추출
print(a[-1,-1])

20
[[ 3  4]
 [ 8  9]
 [13 14]]
[ 6  7  8  9 10]
20


In [48]:
np.maximum(a[1,],a[2,],a[3,]) # 각행 중에 가장 큰 값을 찾음

a1 = np.array([2,3,4])
a2 = np.array([1,5,2])

print(np.maximum(a1,a2)) # 2, 5 , 4
print(np.sum(a1))

array([11, 12, 13, 14, 15])

In [94]:
np.random.choice(10, 5, replace = False) 
# replace = True 기본, False 인 경우 중복 허용 안함
print(np.random.rand(2,3)) # 0 부터 1 사이의 수를 반환
print(np.random.randn(2,3)) # -1 부터 1 까지 정규분포로 반환

a = np.array([5,4,7,8,10])
print(np.argmax(a), a[np.argmax(a)]) # np.argmax() -> 값의 위치 반환

arr = np.array([[0.1,0.8,0.2],[0.3,0.2,0.5],[0.9,0.5,0.3]])
print(arr)
print(np.argmax(arr , axis = 0)) # np.argmax 단독 사용일 경우 전체 위치를 기준으로 반환
print(np.argmax(arr, axis=1))

[[0.18276719 0.10072879 0.90663332]
 [0.51438609 0.68379734 0.44968889]]
[[ 0.18668499 -0.63887929  0.1545255 ]
 [-2.64643361 -0.80903337 -1.37033836]]
4 10
[[0.1 0.8 0.2]
 [0.3 0.2 0.5]
 [0.9 0.5 0.3]]
[2 0 1]
[1 2 0]


In [75]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])
len(x)
print(np.mean(x))
print(np.median(x))
print(np.var(x))
print(np.std(x))
print(np.max(x))
print(np.min(x))
print(np.percentile(x, 25))  # 사분위수 : 1사분위
print(np.percentile(x, 100)) # 사분위수 최댓값

4.8076923076923075
5.0
115.23224852071006
10.734628476137871
23
-24
0.0
23.0


In [78]:
# 난수 발생과 카운팅
np.random.seed() # 시작 숫자를 정해주면 항상 같은 숫자의 난수 발생
np.random.randint(5) # 난수 5개 발생

0

In [77]:
# 데이터의 순서 바꿈 : np.random.shuffle(array)
x = np.arange(10)
print(x)
np.random.shuffle(x)
x

[0 1 2 3 4 5 6 7 8 9]


array([0, 4, 7, 6, 5, 3, 8, 9, 2, 1])

In [79]:
# 샘플링 : np.random.choice(arr 또는 정수, size = 샘플갯수, replace=True, p=None[] 확률)
print(np.random.choice(5, 5, replace=False)) # shuffle 효과
print(np.random.choice(5, 3, replace=False))
print(np.random.choice(5, 10))
print(np.random.choice(5, 10, p=[0.1, 0, 0.1, 0.5, 0.3]))

[4 0 1 3 2]
[1 4 3]
[3 1 2 3 1 3 2 3 3 1]


In [80]:
# randint(row, high=None, size=None) # 정수 난수 발생
print(np.random.randint(10)) # 0과 row 사이의 정수 출력
print(np.random.randint(10, size=5))
print(np.random.randint(10,20, size=5))
print(np.random.randint(10,20, size=(3,5)))

8
[2 3 2 1 9]
[12 12 18 11 15]
[[13 15 19 17 10]
 [10 15 13 11 16]
 [18 14 13 18 14]]


In [81]:
a = np.random.randint(10,100,size=10)  # 10과 100 사이에서 난수 10개 생성하여 추출
mask = (a >= 10) & (a<=30)  # and -> &, or -> |
print(a)
print(mask)
print(a[mask])

[84 10 88 64 87 26 48 37 33 57]
[False  True False False False  True False False False False]
[10 26]


In [82]:
x = np.arange(1,21)

# 3의 배수만 추출
print(x[x % 3 == 0])
# 4로 나눈 나머지값이 1인 숫자 추출
print(x[x % 4 == 1])
# 3의 배수이고 4로 나눈 나머지 값이 1인 숫자 추출
print(x[(x % 3 == 0) & (x % 4 == 1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


In [143]:
import pandas as pd
# 문제) 서울시 구별 연도별 CCTV 설치 파일을 가져와서
# 연도별로 CCTV 설치가 가장 많은 구의 명을 입력
df = pd.read_csv('./dataset/서울시CCTV설치운영현황(자치구)_년도별_211231기준.csv', skiprows = 1, encoding='cp949')
df1 = df.copy()
df1.drop(0, axis=0, inplace = True)
df1.set_index('구분', inplace = True)
df1

df1.drop(df1.columns[0], axis = 1 , inplace = True)

for col in df1.columns :
    df1[col].fillna(0, inplace = True)
df1 = df1.astype('int')

cctv = np.array(df1.iloc[:,1:])
list_max = np.argmax(cctv, axis = 0)

for i , k in enumerate(list_max) :
    print(f'{df1.columns[i]} cctv 설치가 가장 많은 구의 명은 {df1.index[k]} => {df1.iloc[k,i]} 개 입니다.')

2012년 이전 cctv 설치가 가장 많은 구의 명은 서대문구 => 730 개 입니다.
2012년 cctv 설치가 가장 많은 구의 명은 관악구 => 84 개 입니다.
2013년 cctv 설치가 가장 많은 구의 명은 강남구 => 66 개 입니다.
2014년 cctv 설치가 가장 많은 구의 명은 강남구 => 580 개 입니다.
2015년 cctv 설치가 가장 많은 구의 명은 강남구 => 830 개 입니다.
2016년 cctv 설치가 가장 많은 구의 명은 서초구 => 504 개 입니다.
2017년 cctv 설치가 가장 많은 구의 명은 성북구 => 890 개 입니다.
2018년 cctv 설치가 가장 많은 구의 명은 강북구 => 391 개 입니다.
2019년 cctv 설치가 가장 많은 구의 명은 영등포구 => 65 개 입니다.
2020년 cctv 설치가 가장 많은 구의 명은 광진구 => 175 개 입니다.


In [ ]:
for colum in df_seoul.columns :
    for index_name in df_seoul.index:
        if df_seoul.loc[index_name, column] == df_soul.loc[:,column].max() :
            print(f'...')